FROM concourse/concourse

# Create directories for keys
RUN mkdir -p /concourse-keys /concourse-public

# Default entrypoint for the container
ENTRYPOINT ["dumb-init", "/usr/local/concourse/bin/concourse", "web"]
