version: '3'

services:
  router:
    image: nginx:latest
    container_name: router
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - blue
      - green

  blue:
    build:
      context: ./blue
    container_name: blue
    environment:
      - APP_COLOR=blue

  green:
    build:
      context: ./green
    container_name: green
    environment:
      - APP_COLOR=green
