name: Build and Deploy Custom Concourse Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OpenSSH
        run: sudo apt-get install -y openssh-client

      - name: Generate Keys
        run: bash ./generate_keys.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Custom Concourse Web Image
        run: |
          docker build -t custom-concourse-web:latest -f Dockerfile.web .
          docker tag custom-concourse-web:latest ${{ secrets.DOCKER_USERNAME }}/custom-concourse-web:latest

      - name: Push Custom Concourse Web Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/custom-concourse-web:latest

      - name: Build Custom Concourse Worker Image
        run: |
          docker build -t custom-concourse-worker:latest -f Dockerfile.worker .
          docker tag custom-concourse-worker:latest ${{ secrets.DOCKER_USERNAME }}/custom-concourse-worker:latest

      - name: Push Custom Concourse Worker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/custom-concourse-worker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_concourse_web_image: ${{ secrets.DOCKER_USERNAME }}/custom-concourse-web:latest
          TF_VAR_concourse_worker_image: ${{ secrets.DOCKER_USERNAME }}/custom-concourse-worker:latest
