global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'sli_app'
    static_configs:
      - targets: ['sli_app:8000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
