version: '3'
services:
  blue:
    build:
      context: ./blue
    ports:
      - "5001:5000"

  green:
    build:
      context: ./green
    ports:
      - "5002:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green
